### ISSUE TITLE
Does it also work for Last Chaos?

### ISSUE THREAD

**Issue by Akrelion45** [SeriousAlexej/ParametricParticles#3]
Hey. Do you think that release should also work for the Last Chaos Source? 

From what i see most in the Tools seem identical to the Croteam release. 

Can't simply test it right now myself, because of a bug i have in the Last Chaos Serious Editor that prevents me from opening my compilation, thats why ask in general if something speaks against it in terms of compatibility.

**Comment by SeriousAlexej** [comment]
I am not sure if its binary compatible with Last Chaos, the release here is built with VC 6.0.
It might have some binary dependency via following file:
`#include "EntitiesMP/Global.h"`
[From here](https://github.com/SeriousAlexej/ParametricParticles/blob/b3eb9551d16a49105166defe46fe49901666174d/Sources/ParametricParticlesMP/StdH/StdH.h#L4)

It is used for events like `EActivate` and so on.

To find out - you have to try it :)

**Comment by SeriousAlexej** [comment]
@Akrelion45 Actually I guess it wont be compatible, since it is binary linked to the 1.07 version of the `Engine.dll` and uses explicit linking to it via [assembly hacks](https://github.com/SeriousAlexej/ParametricParticles/blob/b3eb9551d16a49105166defe46fe49901666174d/Sources/ParametricParticlesUtils/ParticlesUtils.cpp#L185).
